server.port=9000
spring.application.name=job-search-gateway

spring.cloud.gateway.server.webflux.routes[0].id=job-search
spring.cloud.gateway.server.webflux.routes[0].uri=${JOB_SEARCH_URI}
spring.cloud.gateway.server.webflux.routes[0].predicates[0].name=Path
spring.cloud.gateway.server.webflux.routes[0].predicates[0].args[0]=/job-search/**
spring.cloud.gateway.server.webflux.routes[0].order=0

spring.cloud.gateway.server.webflux.routes[1].id=notification
spring.cloud.gateway.server.webflux.routes[1].uri=${NOTIFICATION_URI}
spring.cloud.gateway.server.webflux.routes[1].predicates[0].name=Path
spring.cloud.gateway.server.webflux.routes[1].predicates[0].args[0]=/notification/**
spring.cloud.gateway.server.webflux.routes[1].order=1

spring.cloud.gateway.server.webflux.routes[2].id=ai
spring.cloud.gateway.server.webflux.routes[2].uri=${AI_URI}
spring.cloud.gateway.server.webflux.routes[2].predicates[0].name=Path
spring.cloud.gateway.server.webflux.routes[2].predicates[0].args[0]=/ai/**
spring.cloud.gateway.server.webflux.routes[2].order=2

logging.level.org.springframework.cloud.gateway=INFO
